Location means cancelled.
lesander/magister-calendar pull request #29
Opened 2016-11-10 19:46 UTC by skillzzjesse

Added a new feature.

Some schools change the location of an appointment to a certain value
instead of canceling the appointment. This new feature checks if the new
location might be that special value and recognises it's cancelled
rather than changed location.

Let's hope it works.

2016-11-10 19:52 UTC, skillzzjesse commented
*Don't mind the typo I made in the branchname 😬*

2017-05-02 08:55 UTC, lesander requested changes
I'm terribly sorry for the delayed response. The PR looks OK, just address these issues and it's set for merging.

2017-05-02 08:55 UTC, lesander commented on magister-calendar.js
> +if (typeof(CONFIG.location_means_cancelled != "object")) {
In `config.json` you set `location_means_cancelled` to an array, not an object.

2017-05-02 08:55 UTC, lesander commented on magister-calendar.js
> +
I wonder if this can be simplified. Your PR adds two `for` loops and they both essentially do the exact same thing.

2017-05-02 08:55 UTC, lesander commented on magister-calendar.js
> +        }
Why do you not `break` this loop if a match was found? Also, please use `===` over `==`.

2017-05-02 08:55 UTC, lesander commented on config.json
> +  "location_means_cancelled": [""],
Can you phrase `location_means_cancelled` differently? And perhaps set it to boolean `false` by default, your feature should only be run if it's is enabled.

2017-05-02 09:03 UTC, jessevdp commented on magister-calendar.js
> +        }
Ehm not sure.... haven't looked at this in forever tbh 😂

2018-11-23 15:46 UTC, Argetan commented
I think this PR can be closed without merging seen that fact that the repository from which it was going to be merged doesn't exist anymore.

2020-03-18 06:31 UTC, closed without merging